Repository coopiteasy/investor-wallet-platform, pull requests merged in 2019-11, with the labels that each got.

#27 [ADD] iwp_base: Filter for structure
  investor_wallet_platform_base/views/loan_issue_view.xml
  investor_wallet_platform_base/views/res_partner_view.xml
Labels: ready to merge

#29 [ADD] iwp_base: Stat about financial products and outstanding
  investor_wallet_platform_base/__manifest__.py
  investor_wallet_platform_base/models/__init__.py
  investor_wallet_platform_base/models/loan_issue.py
  investor_wallet_platform_base/models/partner.py
  investor_wallet_platform_base/models/product.py
  investor_wallet_platform_base/models/res_company.py
  investor_wallet_platform_base/models/res_users.py
  investor_wallet_platform_base/views/res_company_view.xml
  investor_wallet_platform_base/views/res_partner_view.xml
Labels: ready to merge

#35 [FIX] iwp_website: Amount of loan wallet
  iwp_website/controllers/investor_portal.py
Labels: ready to test

#33 12.0 backend configuration structure
  investor_wallet_platform_base/__manifest__.py
  investor_wallet_platform_base/data/mail_template_data.xml
  investor_wallet_platform_base/models/__init__.py
  investor_wallet_platform_base/models/coop.py
  investor_wallet_platform_base/models/coop_membership.py
  investor_wallet_platform_base/models/invoice.py
  investor_wallet_platform_base/models/ir_mail_server.py
  investor_wallet_platform_base/models/loan_issue.py
  investor_wallet_platform_base/models/mail_template.py
  investor_wallet_platform_base/models/partner.py
  investor_wallet_platform_base/report/cooperator_certificat.xml
  investor_wallet_platform_base/report/cooperator_to_certificat.xml
  investor_wallet_platform_base/report/easy_my_coop_report.xml
  investor_wallet_platform_base/views/ir_mail_server_view.xml
  investor_wallet_platform_base/views/menus.xml
  investor_wallet_platform_base/views/product_view.xml
  investor_wallet_platform_base/views/res_partner_view.xml
Labels: need review
